### PR TITLE
get arrayBuffer directly from response.arrayBuffer()

### PR DESCRIPTION
**Pull request by Priestch**

### CODE REVIEW

**Comment by paulo-coutinho** [comment]
Hi, this solution was tested?

**Comment by paulo-coutinho** [comment]
@cetinsert can you look this solution? it is correct in html5 world.

**Comment by Priestch** [comment]
> Hi, this solution was tested?

Yes, already used in real project. First want to improve performance, but it seems only make code more simple.

**Review by paulo-coutinho — APPROVED** [review]

**Comment by cetinsert** [comment]
@paulo-coutinho – sorry for the late reply, and yes the commit does use the most direct way to go from `fetch` to `Uint8Array`.

**Pull request merged**
